# 예외 처리

## 오류는 어떤 때 발생하는가?

try, except를 사용해 예외적으로 오류를 처리할 수 있음



실제 프로그램에서 자주 발생하는 오류

- FileNotFoundError
- ZeroDivisionError
- IndexError



## 오류 예외 처리 기법

### try, except 문

```python
try:
    ...
# [ ] 기호는 괄호 안의 내용을 생략할 수 있다는 관례 표기법
except [발생 오류[as 오류 메시지 변수]]:
    ...
```

- try 블록에서 오류가 발생하면 except 블록이 수행됨
- try 블록에서 오류가 발생하지 않으면 except 블록은 수행되지 않음



except 구문 사용 방법

1. try, except만 쓰는 방법

   ```python
   try:
       ...
   except:
       ...
   ```

   - 오류 종류에 상관없이 오류가 발생하면 except 블록 수행

2. 발생 오류만 포함한 except 문

   ```python
   try:
       ...
   except 발생 오류:
       ...
   ```

   - 오류가 발생했을 때 except 문에 미리 정해놓은 오류 이름과 일치할 때만 except 블록 수행

3. 발생 오류와 오류 메시지 변수까지 포함한 except 문

   ```python
   try:
       ...
   except 발생 오류 as 오류 메시지 변수:
       ...
   ```

   - 오류 메시지의 내용까지 알고 싶을 때 사용

   ```python
   try:
       4 / 0
   except ZeroDivisionError as e:
       print(e) # division by zero
   ```

   - 4를 0으로 나눌 때 ZeroDivisionError가 발생하여 except 블록 실행
   - 변수 e에 담기는 오류 메시지를 출력



### try ... finally

finally절

- try 문 수행 도중 예외 발생 여부에 상관없이 항상 수행
- 사용한 리소스를 close 할 때 많이 사용



```python
f = open('foo.txt', 'w')
try:
    # 무언가를 수행
finally:
    f.close()
```

- foo.txt 파일을 쓰기 모드로 연 후 try 문을 수행
- 예외 발생 여부와 상관없이 finally절에서 f.close()로 열린 파일을 닫을 수 있음



### 여러 개의 오류 처리하기

```python
try:
    ...
except 발생 오류1:
    ...
except 발생 오류2:
    ...
```



ZeroDivisionError와 IndexError 처리

```python
try:
    a = [1, 2]
    # IndexError
    print(a[3])
    # IndexError가 먼저 발생했으므로, ZeroDivisionError 오류는 발생하지 x
    4 / 0
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
except IndexError:
    print("인덱싱 할 수 없습니다.")
```

오류 메시지도 같이 가져오기

```python
try:
    a = [1, 2]
    print(a[3])
    4 / 0
except ZeroDivisionError as e:
    print(e)
except IndexError as e:
    print(e) # list index out of range
```



ZeroDivisionError와 IndexError 동시에 처리

```python
try:
    a = [1, 2]
    print(a[3])
    4 / 0
# 괄호를 사용해 함께 묶어 처리
except (ZeroDivisionError, IndexError) as e:
    print(e)
```



## 오류 회피하기

특정 오류가 발생할 경우 그냥 통과시킬 때

```python
try:
    f = open("없는 파일", 'r')
except FileNotFoundError:
    # 오류를 그냥 회피
    pass
```



## 오류 일부러 발생시키기

raise 명령어를 사용해 오류를 강제로 발생시킴

```python
# Bird 클래스를 상속받는 자식 클래스는 반드시 fly 함수를 구현
class Bird:
    def fly(self):
        # 파이썬 내장 오류 NotImplementedError
        # 꼭 작성해야 하는 부분이 구현되지 않았을 때, 일부러 오류를 일으키기 위해 사용
        raise NotImplementedError
```



```python
# Eagle 클래스는 Bird 클래스를 상속받음
class Eagle(Bird):
    pass

eagle = Eagle()
eagle.fly()
```

- Eagle 클래스에서 fly 함수를 구현하지 않았으므로, Bird 클래스의 fly 함수가 호출
- raise 문에 의해 NotImplementedError 발생



```python
class Eagle(Bird):
    def fly(self):
        print("very fast")
        
eagle = Eagle()
eagle.fly() # very fast
```

- 메소드 오버라이딩: 상속받는 클래스에서 함수를 재구현

- NotImplementedError가 발생하지 않게 하기 위해 Eagle 클래스에 fly 함수를 구현
- 오류 없이 출력



[점프 투 파이썬/ 05장 파이썬 날개달기/ 05-4 예외 처리](https://wikidocs.net/30)

## 예외 만들기

프로그램 수행 도중 특수한 경우에만 예외 처리를 하기 위해 예외를 만들어서 사용

파이썬 내장 클래스 Exception 클래스를 상속하여 만듦

```python
class MyError(Exception):
    pass
```

별명을 출력해주는 함수 작성

```python
def say_nick(nick):
    if nick == '바보':
        raise MyError()
    print(nick)
```

say_nick 함수 호출

```python
say_nick("천사")
say_nick("바보")
```

- "천사"가 한 번 출력된 후 MyError 발생

예외 처리 기법을 사용하여 MyError 발생을 예외 처리

```python
try:
    say_nick("천사")
    say_nick("바보")
except MyError:
    print("허용되지 않는 별명입니다.")
# 천사
# 허용되지 않는 별명입니다.
```

오류 메시지 사용

```python
try:
    say_nick("천사")
    say_nick("바보")
except MyError as e:
    print(e)
```

- print(e)로 오류 메시지 출력되지 않음

```python
class MyError(Exception):
    def __str__(self):
        return "허용되지 않는 별명입니다."
```

- 오류 메시지를 출력했을 때 오류 메시지가 보이게 하기 위해 오류 클래스에 `__str__` 메소드 구현
- `__str__`메소드: print(e)처럼 오류 메시지를 print 문으로 출력할 경우 호출되는 메소드

- "허용되지 않는 별명입니다." 오류 메시지 출력